services:
  instagram-scraper:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      NORD_VPN_SOCKS5_HOST: ${NORD_VPN_SOCKS5_HOST:-}
      NORD_VPN_SOCKS5_PORT: ${NORD_VPN_SOCKS5_PORT:-1080}
      NORD_PROXY_POOL: ${NORD_PROXY_POOL:-}
      SCRAPER_MIN_DELAY_SECONDS: ${SCRAPER_MIN_DELAY_SECONDS:-2.5}
      SCRAPER_MAX_DELAY_SECONDS: ${SCRAPER_MAX_DELAY_SECONDS:-6.5}
      SCRAPER_TIMEOUT_SECONDS: ${SCRAPER_TIMEOUT_SECONDS:-20}
      SCRAPER_RETRIES: ${SCRAPER_RETRIES:-3}
      PROXY_RETRY_LIMIT: ${PROXY_RETRY_LIMIT:-5}
      PROXY_BACKOFF_SECONDS: ${PROXY_BACKOFF_SECONDS:-2}
      INSTAGRAM_SESSIONID: ${INSTAGRAM_SESSIONID:-}
      INSTAGRAM_CSRFTOKEN: ${INSTAGRAM_CSRFTOKEN:-}
      INSTAGRAM_APP_ID: ${INSTAGRAM_APP_ID:-936619743392459}
      INSTAGRAM_USERNAME: ${INSTAGRAM_USERNAME:-}
      INSTAGRAM_PASSWORD: ${INSTAGRAM_PASSWORD:-}
      INSTAGRAM_COOKIE_FILE: ${INSTAGRAM_COOKIE_FILE:-/data/instagram_cookies.json}
      DATABASE_PATH: ${DATABASE_PATH:-/data/scrapes.db}
      IMAGES_DIR: ${IMAGES_DIR:-/data/images}
    volumes:
      - ./data:/data
    restart: unless-stopped
